### ISSUE TITLE
The link to the visual backbone cannot be opened

### ISSUE THREAD

**Issue by dym1996** [sucv/Visual_to_EEG_Cross_Modal_KD_for_CER#1]
Hello, I am a graduate student in the field of emotion recognition, when I run the code you uploaded, I found that the link to the visual backbone cannot be opened, I hope you can re-upload it, thank you for sharing the code.

**Comment by sucv** [comment]
Did you mean `res50_ir_0.874.pth`? I just checked the link, and it still works.

https://drive.google.com/file/d/1izzZNtRIGchbyhf-aiTKB950IH1ZeJ4C/view?usp=share_link
